services:
  backend:
    build: ./backend
    ports:
      - "4000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data  

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  api:
    build: ./api
    ports:
      - "8002:8002"
    depends_on:
      - backend

volumes:
  db_data:
    driver: local 
